In [2]:
import pandas as pd

In [70]:
model = pd.read_csv('model.csv')

FileNotFoundError: [Errno 2] File b'model.csv' does not exist: b'model.csv'

In [73]:
l = [1,2,3,4,5,6,7,8,9,10,11]
l = pd.Series([l.index(i)+1 for i in range(1, len(l)+1)] + [1])
pd.Series([(l * model[col]).sum() for col in model]).idxmax() + 1

3

In [74]:
l

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11     1
dtype: int64

In [75]:
pd.Series([(l * model[col]).sum() for col in model])

0   -2.900991
1   -2.810821
2    1.279173
3   -5.910897
4   -6.252937
5   -5.702798
6   -2.000820
dtype: float64

In [71]:
model

,1 Safety,2 Old Dogs,3 Toys,4 Special Needs,5 Poop Haters,6 Nurturers,7 Dads
0,0.063862,0.032950,-0.354037,0.002875,0.152324,0.198450,0.002612
1,0.069796,0.104873,-0.294498,0.056825,0.012921,0.020212,0.117347
2,-0.128057,0.018567,-0.060444,0.103966,0.196026,-0.112462,0.157911
3,0.109374,0.010512,0.002210,0.031496,-0.037053,0.095093,-0.334107
4,-0.506632,0.013806,0.077370,0.158432,0.227061,0.036885,0.209744
5,0.117544,-0.245095,0.111308,0.017230,0.129275,-0.205154,0.173592
6,0.049947,-0.304973,0.135178,0.062087,-0.002618,0.179640,-0.194026
7,0.073610,0.070148,0.011769,0.085217,-0.029643,0.040833,-0.365351
8,0.097783,0.103987,0.173066,0.022180,-0.794889,0.122094,-0.126082
9,0.058445,-0.015105,0.065357,-0.227517,0.147055,-0.163875,0.202582
10,-0.049837,0.183187,0.060752,-0.220161,0.028766,-0.136321,0.139104
11,-3.184681,-2.975987,-2.579833,-3.979868,-3.159430,-4.482868,-1.605933

In [44]:
list(l).index()

TypeError: index() takes at least 1 argument (0 given)

In [32]:
model.to_clipboard()

In [36]:
pd.DataFrame(model.values)

           0         1         2         3         4         5         6
0   0.063862  0.032950 -0.354037  0.002875  0.152324  0.198450  0.002612
1   0.069796  0.104873 -0.294498  0.056825  0.012921  0.020212  0.117347
2  -0.128057  0.018567 -0.060444  0.103966  0.196026 -0.112462  0.157911
3   0.109374  0.010512  0.002210  0.031496 -0.037053  0.095093 -0.334107
4  -0.506632  0.013806  0.077370  0.158432  0.227061  0.036885  0.209744
5   0.117544 -0.245095  0.111308  0.017230  0.129275 -0.205154  0.173592
6   0.049947 -0.304973  0.135178  0.062087 -0.002618  0.179640 -0.194026
7   0.073610  0.070148  0.011769  0.085217 -0.029643  0.040833 -0.365351
8   0.097783  0.103987  0.173066  0.022180 -0.794889  0.122094 -0.126082
9   0.058445 -0.015105  0.065357 -0.227517  0.147055 -0.163875  0.202582
10 -0.049837  0.183187  0.060752 -0.220161  0.028766 -0.136321  0.139104
11 -3.184681 -2.975987 -2.579833 -3.979868 -3.159430 -4.482868 -1.605933